apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: httpd
  name: clarksdaleonly
  namespace: simple-app
spec:
  clusterSelector:
    matchLabels:
      clusterid: cluster1
